// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
import 'dart:core';
import 'package:food_delivery_app/data/services/reflect.dart' as prefix0;
import 'package:food_delivery_app/features/authentication/models/auth/token.dart'
    as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Token',
            r'.Token',
            134217735,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 3],
            const <int>[8, 3, 9, 10, 11, 2, 4, 5, 6, 7],
            const <int>[],
            1,
            {},
            {},
            {},
            0,
            0,
            const <int>[],
            const <Object>[prefix0.reflector, prefix0.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'Object',
            r'dart.core.Object',
            134217735,
            1,
            const prefix0.Reflector(),
            const <int>[8, 12, 9, 10, 11],
            const <int>[8, 12, 9, 10, 11],
            const <int>[],
            null,
            {},
            {},
            {},
            1,
            1,
            const <int>[],
            const [],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'access', 134348805, 0, const prefix0.Reflector(),
            -1, -1, -1, null, const []),
        r.VariableMirrorImpl(r'refresh', 134348805, 0,
            const prefix0.Reflector(), -1, -1, -1, null, const []),
        r.MethodMirrorImpl(r'toJson', 35651586, 0, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, 0, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 4),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 5),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 6),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 1, 7),
        r.MethodMirrorImpl(r'==', 2097154, 1, -1, -1, -1, null, const <int>[2],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, 1, -1, -1, -1, null,
            const <int>[3], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, 1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, 1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, 1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'_access', 134348902, 5,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'_refresh', 134348902, 7,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'other', 134348806, 8, const prefix0.Reflector(),
            1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'invocation', 134348806, 9,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null)
      ],
      <Type>[prefix1.Token, Object],
      2,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'access': (dynamic instance) => instance.access,
        r'refresh': (dynamic instance) => instance.refresh
      },
      {
        r'access=': (dynamic instance, value) => instance.access = value,
        r'refresh=': (dynamic instance, value) => instance.refresh = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse(
                'package:food_delivery_app/features/authentication/models/auth/token.dart'),
            const prefix0.Reflector(),
            const <int>[],
            {},
            {},
            const [],
            null),
        r.LibraryMirrorImpl(
            r'dart.core',
            Uri.parse(r'reflectable://1/library dart:core'),
            const prefix0.Reflector(),
            const <int>[],
            {},
            {},
            const [],
            null)
      ],
      []),
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Token',
            r'.Token',
            134217735,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 2, 3, 8],
            const <int>[9, 3, 10, 11, 12, 2, 4, 5, 6, 7],
            const <int>[],
            -1,
            {},
            {},
            {
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.Token.fromJson(json) : null
            },
            0,
            0,
            const <int>[],
            const <Object>[prefix0.reflector, prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'access', 134348805, 0,
            const prefix0.JsonSerializable(), -1, -1, -1, null, const []),
        r.VariableMirrorImpl(r'refresh', 134348805, 0,
            const prefix0.JsonSerializable(), -1, -1, -1, null, const []),
        r.MethodMirrorImpl(r'toJson', 35651586, 0, -1, -1, -1, null,
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'toString',
            2097154,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[],
            const prefix0.JsonSerializable(),
            const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 4),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 0, 5),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 6),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 1, 7),
        r.MethodMirrorImpl(r'fromJson', 0, 0, -1, -1, -1, null, const <int>[0],
            const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, -1, -1, null, const <int>[3],
            const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1, null,
            const <int>[4], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'json',
            151126022,
            8,
            const prefix0.JsonSerializable(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_access',
            134348902,
            5,
            const prefix0.JsonSerializable(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_refresh',
            134348902,
            7,
            const prefix0.JsonSerializable(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            9,
            const prefix0.JsonSerializable(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            10,
            const prefix0.JsonSerializable(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null)
      ],
      <Type>[prefix1.Token],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'access': (dynamic instance) => instance.access,
        r'refresh': (dynamic instance) => instance.refresh
      },
      {
        r'access=': (dynamic instance, value) => instance.access = value,
        r'refresh=': (dynamic instance, value) => instance.refresh = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse(
                'package:food_delivery_app/features/authentication/models/auth/token.dart'),
            const prefix0.JsonSerializable(),
            const <int>[],
            {},
            {},
            const [],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
